version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    restart: unless-stopped 