
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WITH_XDEBUG=true
        - WITH_GIT=true
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    environment:
      - PHP_MEMORY_LIMIT=2G
      - XDEBUG_MODE=debug
      - XDEBUG_CONFIG=client_host=host.docker.internal
    volumes:
      - ~/.ssh:/root/.ssh:ro
      - ./src:/var/www/html
    ports:
      - "80:80"
    networks:
      - laravel-network
    depends_on:
      - db
    command: bash -c "chmod -R 777 /var/www/html/storage /var/www/html/bootstrap/cache && apache2-foreground"

  db:
    image: postgres:15
    container_name: laravel-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: your_postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  postgres_data: 