# without this line, vscode wont show the "Run All Services" button
name: pakistani-map
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WITH_XDEBUG=true
        - WITH_GIT=true
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    environment:
      - PHP_MEMORY_LIMIT=2G
      - XDEBUG_MODE=debug
      - XDEBUG_CONFIG=client_host=localhost
      - LOG_CHANNEL=stderr
    volumes:
      - ~/.ssh:/root/.ssh:ro
      - ./src:/var/www/html
    configs:
      - source: apache_vhost
        target: /etc/apache2/sites-available/000-default.conf
    ports:
      - "80:80"
      - "9003:9003"
    networks:
      - laravel-network
    depends_on:
      - db
    # 1: this is because we mount the source code, and has a different owner, and will be written to by laravel templates cache engine
    # 2: this is to silence apache warning
    # 3: this is the actual command to start apache
    command: bash -c "
        chmod -R 777 /var/www/html/storage /var/www/html/bootstrap/cache &&
        echo 'ServerName 127.0.0.1' >> /etc/apache2/apache2.conf &&
        apache2-foreground 
      "

  db:
    image: postgres:15
    container_name: laravel-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: your_postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  postgres_data:

configs:
  apache_vhost:
    content: |
      <VirtualHost *:80>
          ServerAdmin webmaster@localhost
          DocumentRoot /var/www/html/public

          <Directory /var/www/html/public>
              Options Indexes FollowSymLinks
              AllowOverride All
              Require all granted
          </Directory>

          ErrorLog /dev/stderr
          CustomLog /dev/stdout combined
      </VirtualHost> 